"""Remote config and anonymous telemetry.

The author's server serves the catalogue (slg_sync_server) and now two small
extras: a config.json that carries feature flags + announcements, and a /report
endpoint that accepts one-line anonymous events. Everything here is best-effort:
a config fetch that fails returns {}, a report that fails is dropped, and
neither ever raises into the GUI.

Privacy: the payload carries an anonymous device id and aggregate numbers only.
No nickname, no game name, no cover, no comment text is ever sent.
"""

import json
import os
import threading
import urllib.error
import uuid
import slg_db
import slg_scrape
from slg_sync_server import SERVER_BASE

PREF_DEVICE_ID = "anon.device_id"
PREF_ANNOUNCE_SEEN = "remote.announce_seen"

# Bumped when the report payload shape changes, so the aggregate can tell stale
# clients apart from current ones.
PAYLOAD_VERSION = "1"


def device_id(conn):
    """The machine's anonymous id, generated once and stored in prefs.

    A random UUID, not derived from any hardware or account: it only exists to
    count distinct installs, and it can be regenerated by deleting the pref.
    """
    ident = slg_db.get_pref(conn, PREF_DEVICE_ID)
    if not ident:
        ident = uuid.uuid4().hex
        slg_db.set_pref(conn, PREF_DEVICE_ID, ident)
    return ident


def fetch_config(timeout=6):
    """The server's config.json as a dict, or {} on any failure."""
    try:
        raw = slg_scrape.http_get(
            SERVER_BASE + "/config.json", timeout=timeout, direct=True)
        data = json.loads(raw.decode("utf-8", "replace"))
        return data if isinstance(data, dict) else {}
    except Exception:  # noqa: BLE001 - config is a nicety, never an error
        return {}


def report(conn, event_type, data=None):
    """Fire an anonymous event at the server, off the UI thread.

    Returns immediately: the POST runs on a daemon thread and a failure is
    dropped. There is deliberately no queue or retry - a lost report costs
    nothing, and a queue would just pile up offline events to dump later.
    """
    payload = {
        "v": PAYLOAD_VERSION,
        "device": device_id(conn),
        "app": "slgking",
        "ts": slg_db._now(),
        "event": event_type,
        "data": data or {},
    }

    def _send():
        try:
            slg_scrape.http_post(
                SERVER_BASE + "/report", payload, timeout=6, direct=True)
        except Exception:  # noqa: BLE001 - telemetry must never raise
            pass

    threading.Thread(target=_send, daemon=True).start()


def stats_key_path():
    """Where the stats key lives: %LOCALAPPDATA%/slgking/stats_key.txt.

    Public because the panel names the file when the server rejects the key -
    the fix is editing this path, so the message has to say which path.
    """
    return os.path.join(slg_db.app_dir(), "stats_key.txt")


def stats_key():
    """The developer's stats-viewing key, from a machine-local file, or None.

    Kept separate from the developer secret on purpose: this read-only key is
    sent in an HTTPS request header; the developer secret never leaves the machine.
    """
    try:
        with open(stats_key_path(), "r", encoding="utf-8") as fh:
            value = fh.read().strip()
            return value if value else None
    except OSError:
        return None


def fetch_stats(timeout=8):
    """(status, stats) for the developer-only read panel. Never raises.

    The status exists because every one of these failures used to look the same
    on screen - an empty panel - while needing a completely different fix:

      ok       the server answered, stats is the aggregate (possibly empty);
      locked   deployed, but its SLGKING_STATS_KEY is not this machine's key;
      missing  /stats.json 404s, which means the box still runs an old
               serve_catalog and has never been deployed with /report at all;
      offline  no answer, or an answer that is not JSON.
    """
    key = stats_key()
    try:
        raw = slg_scrape.http_get(
            SERVER_BASE + "/stats.json", timeout=timeout, direct=True,
            headers={"X-SLG-Admin-Key": key} if key else None)
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return ("missing", None)
        if exc.code == 401:
            return ("locked", None)
        return ("offline", None)
    except Exception:  # noqa: BLE001 - the panel renders the status text
        return ("offline", None)
    try:
        data = json.loads(raw.decode("utf-8", "replace"))
    except ValueError:
        return ("offline", None)
    if not isinstance(data, dict):
        return ("offline", None)
    if data.get("locked"):
        return ("locked", None)
    return ("ok", data)
