"""Remote config and anonymous telemetry.

The author's server serves the catalogue (slg_sync_server) and now two small
extras: a config.json that carries feature flags + announcements, and a /report
endpoint that accepts one-line anonymous events. Everything here is best-effort:
a config fetch that fails returns {}, a report that fails is dropped, and
neither ever raises into the GUI.

Privacy: the payload carries an anonymous device id and aggregate numbers only.
No nickname, no game name, no cover, no comment text is ever sent.
"""

import json
import threading
import uuid
from datetime import datetime, timedelta, timezone
import slg_db
import slg_scrape
import slg_sync_server
from slg_sync_server import SERVER_BASE

PREF_DEVICE_ID = "anon.device_id"
PREF_ANNOUNCE_SEEN = "remote.announce_seen"

# Bumped when the report payload shape changes, so the aggregate can tell stale
# clients apart from current ones.
PAYLOAD_VERSION = "1"
CHINA_TZ = timezone(timedelta(hours=8))


def device_id(conn):
    """The machine's anonymous id, generated once and stored in prefs.

    A random UUID, not derived from any hardware or account: it only exists to
    count distinct installs, and it can be regenerated by deleting the pref.
    """
    ident = slg_db.get_pref(conn, PREF_DEVICE_ID)
    if not ident:
        ident = uuid.uuid4().hex
        slg_db.set_pref(conn, PREF_DEVICE_ID, ident)
    return ident


def fetch_config(timeout=6):
    """The server's config.json as a dict, or {} on any failure."""
    try:
        raw = slg_sync_server._server_http_get(
            SERVER_BASE + "/config.json", timeout=timeout)
        data = json.loads(raw.decode("utf-8", "replace"))
        return data if isinstance(data, dict) else {}
    except Exception:  # noqa: BLE001 - config is a nicety, never an error
        return {}


def report(conn, event_type, data=None):
    """Fire an anonymous event at the server, off the UI thread.

    Returns immediately: the POST runs on a daemon thread and a failure is
    dropped. There is deliberately no queue or retry - a lost report costs
    nothing, and a queue would just pile up offline events to dump later.
    """
    payload = {
        "v": PAYLOAD_VERSION,
        "device": device_id(conn),
        "app": "slgking",
        # Use an explicit offset so the server can bucket reports in
        # Asia/Shanghai even when this machine's OS timezone differs.
        "ts": datetime.now(CHINA_TZ).isoformat(timespec="seconds"),
        "event": event_type,
        "data": data or {},
    }

    def _send():
        try:
            slg_scrape.http_post(
                SERVER_BASE + "/report", payload, timeout=6, direct=True)
        except Exception:  # noqa: BLE001 - telemetry must never raise
            pass

    threading.Thread(target=_send, daemon=True).start()
